### ISSUE TITLE
yildiraykoyuncu: Incremental Development, week 1, homework

### ISSUE THREAD

**Issue by yildiraykoyuncu** [HackYourFutureBelgium/class-9-10#136]
# Week 1

## Incremental Development

- [assignments](https://github.com/yildiraykoyuncu/incremental-development/tree/master/week-1)

## Prep Work
- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths
- [x]  Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

### Isolate

- [x] `New_ group intro repository` [repo](https://github.com/yildiraykoyuncu/group-zoom) [live]( https://yildiraykoyuncu.github.io/group-zoom/.)

### Integrate
- [x] `Semantic-Layout` [starter repo](https://github.com/hackyourfuturebelgium/w3-validation-template) (project starter repo) [live](https://yildiraykoyuncu.github.io/semantic-layout-exercise/) [repo](https://github.com/yildiraykoyuncu/semantic-layout-exercise)

---

### Suggested Study

- [x] Git & GitHub

- [x] HTML & CSS

#### Exercises:
 
- [x] :egg: html-css-git-exercises: [repo](https://github.com/yildiraykoyuncu/html-css-git-exercises), [live](https://yildiraykoyuncu.github.io/html-css-git-exercises/)
- [x] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/yildiraykoyuncu/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Project

`:emoji:` `acme-web-design:

- [x] [repo](https://github.com/yildiraykoyuncu/project-acme-web-design)
- [x] [live](https://yildiraykoyuncu.github.io/acme-web-design/index.html)
- [x] [development-strategy](https://github.com/yildiraykoyuncu/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] [A complete README](https://github.com/yildiraykoyuncu/acme-web-design/blob/master/README.md)

**Comment by snicoll** [comment]
@yildiraykoyuncu great job! I am flagging this as done but please review the following.

I can see  you've used PRs to merge your branches via GitHub. There is nothing wrong with that but I'd like you to do that locally to make sure you're comfortable with the workflow. Rather than pushing the branch to GitHub and creating a PR for it, try to merge the branch on your machine (using whatever tool you fancy).

The link to your license file [in the README](https://github.com/yildiraykoyuncu/acme-web-design/blob/master/README.md) is broken.

**Comment by yildiraykoyuncu** [comment]
Thanks a lot. Pushing all the branches to GitHub and creating PR for each of them was very time-consuming. Next time I will merge my branches locally. 👍 😄
