### ISSUE TITLE
Mamé: incremental-development, Week 1

### ISSUE THREAD

**Issue by mametur** [HackYourFutureBelgium/class-9-10#144]
# Week 2

## Incremental-development  Week-1

[assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-1)

## Prep Work
- [X] Git
- [X] Agile Development
- [X] Relative vs. Absolute Paths
- [X] Inspecting the DOM
- [X] HTML 5 Semantic Layout

### In Class

- [x] Isolate: I have understood the exercises
- [x] [team-branch](https://mametur.github.io/team-branching/)
- [x] Integrate: [live](https://mametur.github.io/stopp-watchh/), [source](https://github.com/mametur/stopp-watchh)

---

#### Exercises

- [x] :egg: [repo](https://github.com/mametur/html-css-git-exercises/tree/master/week-1)
- [ ] :hatching_chick: [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/) 
- [ ] :hatched_chick: [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)

---

### Project

project name: acme-web-design

- [x] [repo](https://github.com/mametur/acme-web-design)
- [x] [live](https://mametur.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/mametur/acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by gelilaa** [comment]
oh i'm really sorry. i didnt even know what i did.

**Comment by snicoll** [comment]
@mametur nice job. Great styling on the class exercise although I am not sure what you've tried to do with the stop watch thing.

You have 37 checkboxes in your description, the idea was to stick to the template (17) so that we can clearly see how far you are. Please take that into account going forward.

There are HTML validation errors for [stop watch](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fmametur.github.io%2Fstopp-watchh%2F) and [acme web design](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmametur.github.io%2Facme-web-design%2F)

Your development strategy is quite complete. Remember that the goal is to describe what value each step brings to the site

I can see you've used PRs to merge your branches via GitHub. There is nothing wrong with that but I'd like you to do that locally to make sure you're comfortable with the workflow. Rather than pushing the branch to GitHub and creating a PR for it, try to merge the branch on your machine (using whatever tool you fancy).

Can you please have a look to the HTML validation errors?

**Comment by mametur** [comment]
@snicoll Thanks I fixed HTML validation errors and also reduce assignment checklist

**Comment by snicoll** [comment]
Great job @mametur!
