### ISSUE TITLE
Aleksandra: Incremental Development , week 1, homework

### ISSUE THREAD

**Issue by aleks2407** [HackYourFutureBelgium/class-9-10#147]
## **Prep Work**

- [x] Git
- [x] Agile Development
- [x] Relative vs. Absolute Paths
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

## **Lesson**
- [x] Project semantic layout: [source](https://github.com/aleks2407/HYF-semantic-layout), [live](https://aleks2407.github.io/HYF-semantic-layout/)
- [x] Project GroupIntro-branches: [source](https://github.com/aleks2407/HYF-TeamIntro-Branches), [live](https://aleks2407.github.io/HYF-TeamIntro-Branches/)

## **Exercises**
* - [x] 🥚 html-css-git-exercises - Week 1: [source](https://github.com/aleks2407/html-css-git-exercises)
* - [ ] 🐣 HTML-CSS-Practice-Problems
* - [ ] 🐥 css-exercises

#### `acme-web-design`

- [x] [source](https://github.com/aleks2407/HYF-acme-web-design)
- [x] [live](https://aleks2407.github.io/HYF-acme-web-design/)
- [x] [development-strategy](https://github.com/aleks2407/HYF-acme-web-design/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/aleks2407/HYF-acme-web-design/blob/master/README.md)

**Comment by snicoll** [comment]
@aleks2407 great work! I am flagging this as done but please consider what follows.

I can see you've used PRs to merge your branches via GitHub. There is nothing wrong with that but I'd like you to do that locally to make sure you're comfortable with the workflow. Rather than pushing the branch to GitHub and creating a PR for it, try to merge the branch on your machine (using whatever tool you fancy).

Your [development strategy](https://github.com/aleks2407/HYF-acme-web-design/blob/master/development-strategy.md) is missing a description for each step. You had it for step 0. It is important to be able to summarize the purpose of each task as it will help you structure your work going forward.

**Comment by aleks2407** [comment]
Thanks a lot @snicoll ! i will try to improve my dev-strategy during next week accordingly.
I'm just more confident with PR, it's kind of more visual for me. But I will try what you suggested next time!
