### ISSUE TITLE
Pavel Bidenko: incremantal development, week 1, homework

### ISSUE THREAD

**Issue by pavelbidenko2018** [HackYourFutureBelgium/class-9-10#156]
# Week 1 

## Incremental Development

- [assignments](https://github.com/hackyourfuturebelgium/incremental-development/tree/master/week-1)

## Prep Work

- [x] Git  
* [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV); 
* [The Net Ninja](https://www.youtube.com/watch?v=QV0kVNvkMxc&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=8); 
* [Atomic Commits](https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git)
- [x] Agile Development
- [x] Relative vs. Absolute Paths
- [x] Inspecting the DOM
- [x] HTML 5 Semantic Layout

---

## In Class

- [x] Isolate: [repo with exercise](https://github.com/pavelbidenko2018/isolate)
- [x] Integrate: [live](https://pavelbidenko2018.github.io/Integrated), [source](https://github.com/pavelbidenko2018/Integrated)

---

### Suggested Study

- [x] Git & GitHub
- [x] HTML & CSS

#### Exercises:

- [x] :egg:  [html-css-git-exercises](https://github.com/pavelbidenko2018/html-css-git-exercises/tree/master/week-1)  
- [x] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/pavelbidenko2018/HTML-CSS-Practice-Problems)

### Project

project name: acme-web-design

- [x] [repo](https://github.com/pavelbidenko2018/acme-web-design)
- [x] [live](https://pavelbidenko2018.github.io/acme-web-design/)
- [x] [development-strategy](https://github.com/pavelbidenko2018/acme-web-design/tree/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete [README](https://github.com/pavelbidenko2018/acme-web-design/tree/master/README.md)

**Comment by snicoll** [comment]
@pavelbidenko2018 great work. I've found a few issues, can you please have look?

* There is a `live` link for " html-css-git-exercises" that should read `repo`
* There is a `live` link for "HTML-CSS-Practice-Problems" that shouldn't be there I suspect. It's 404ing anyway
* There is a warning for your [HTML of the  `acme-web-design`](https://validator.w3.org/nu/?doc=https%3A%2F%2Fpavelbidenko2018.github.io%2Facme-web-design%2F)

I can see you've used PRs to merge your branches via GitHub. There is nothing wrong with that but I'd like you to do that locally to make sure you're comfortable with the workflow. Rather than pushing the branch to GitHub and creating a PR for it, try to merge the branch on your machine (using whatever tool you fancy).

Your development strategy is a bit thin. We'd expect at least a high-level description of each step. This is important as being able to decompose a project into manageable tasks is probably the most important skills that you need to learn. Please review the development strategy and try to provide a high-level goal for each step.

**Comment by pavelbidenko2018** [comment]
@snicoll Thank you very much for your detailed review
- links for exercises checked
- HTML validating warnings removed
- development-strategy file improved

**Comment by snicoll** [comment]
Good job @pavelbidenko2018, thank you!
