### ISSUE TITLE
Kateryna: Incremental development, Week 2, homework

### ISSUE THREAD

**Issue by katerynakim** [HackYourFutureBelgium/class-9-10#218]
# Week 2

## incremental-development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-2)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

---

## In Class

- [x] Isolate: I have understood the exercises: [live](https://katerynakim.github.io/git-workflow-workshop-for-two/ ), [source](https://github.com/katerynakim/git-workflow-workshop-for-two)
- [x] Integrate: [live](https://katerynakim.github.io/git-workflow-for-two-integrate/), [source](https://github.com/katerynakim/git-workflow-for-two-integrate)

---

### Suggested Study

- [ ] Git & GitHub
- [ ] Responsive Design
- [ ] CLI
 
### Exercises:

- [x] 🥚 html-css-git-exercises - Week 2: [repo](https://github.com/katerynakim/html-css-git-exercises/tree/master/week-2), [live](https://katerynakim.github.io/html-css-git-exercises/)
- [ ] 🐣 HTML-CSS-Practice-Problems: [repo](https://github.com/your-user-name/exercise-name), [live](https://your-user-name.github.io/exercise-name/)
- [ ] 🐥 css-exercises

#### app-theme

- [x] [repo](https://github.com/katerynakim/app-theme)
- [x] [live](https://katerynakim.github.io/app-theme/)
- [x] [development-strategy](https://github.com/katerynakim/app-theme/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] A complete README

**Comment by otagi** [comment]
Good code, and excellent branching flow!

Can you fix these minor issues:
- The contact link in the main menu is broken: it goes to `contact.html`, but the actual file is named `contacts.html`.
- You're using `<html lang="zxx">`. Since the page text is in English, let's declare it as such with `<html lang="en">` instead.
- The wireframe image in the development strategy does not show. Its URL should use a `/` (forward slash) instead of a `\` (backward slash).

**Comment by katerynakim** [comment]
Hello Tiago, 

Thank you for your verification.
Kindly please check if all the issues are solved.

**Comment by otagi** [comment]
Perfect! Thank you for these fixes, Kateryna.
