### ISSUE TITLE
Miroslav Veljanoski: Incremental Development, week 2, homework

### ISSUE THREAD

**Issue by miroslavveljanoski** [HackYourFutureBelgium/class-9-10#239]
# Week 2

## Incremental Development

- [assignments](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-2#assignments)

## Prep Work

- [x] Collaborating on GitHub
- [x] WireFrames
- [x] Pair Programming

---

## In Class

- [x] Isolate: I have understood the exercises [live](https://miroslavveljanoski.github.io/miroslav-harun/), [source](https://github.com/miroslavveljanoski/miroslav-harun)
- [x] Integrate: [live](https://harunaltunhr.github.io/integrate-week2/), [source](https://github.com/harunaltunhr/integrate-week2)

---

### Suggested Study

- [x] Git & GitHub
- [ ] Responsive Design
- [ ] CLI

### Exercises:

- [x] :egg: [html-css-git-exercises](https://github.com/miroslavveljanoski/html-css-git-exercises/tree/master/week-2) - Week 2
- [x] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/miroslavveljanoski/HTML-CSS-Practice-Problems)
- [ ] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Project

**I'm still working on the project, but it will be finished until the end of this day - Saturday** :smile: 

`app-theme`

- [x] [repo](https://github.com/miroslavveljanoski/app-theme)
- [x] [live](https://miroslavveljanoski.github.io/app-theme/)
- [x] [development-strategy](https://github.com/miroslavveljanoski/app-theme/blob/master/development-strategy.md)
- [x] One branch per step in my `development-strategy.md`
- [x] One closed Issue per step in my `development-strategy.md`
- [x] One closed Pull Request per step in my `development-strategy.md`
- [ ] A complete README

**Comment by snicoll** [comment]
Excellent work @miroslavveljanoski, I like that you add issue with a clear description of the goal and the fact you play the reviewer in your PR. Keeping an history of what we do and why we do it is very important so that each team member understands what is going.

I saw that none of your commit had that special GitHub instructions to link to an issue (and eventually close it). If you have trouble creating multi-line commit messages we can have a look together. If that's an oversight, create a dummy repo on your account and give it a try to make sure you're comfortable with this process.

**Comment by miroslavveljanoski** [comment]
> Excellent work @miroslavveljanoski, I like that you add issue with a clear description of the goal and the fact you play the reviewer in your PR. Keeping an history of what we do and why we do it is very important so that each team member understands what is going.
> 
> I saw that none of your commit had that special GitHub instructions to link to an issue (and eventually close it). If you have trouble creating multi-line commit messages we can have a look together. If that's an oversight, create a dummy repo on your account and give it a try to make sure you're comfortable with this process.

Thanks for the feedback @snicoll . About the linking a commit to an issue, honestly, I'm not sure in which commit message should I put that extra message. In a real situation when I develop a particular step on a new branch, it happens to have several commits before push the branch to Github. Does it matter in which commit message I will put that extra message in order to link with the issue? Should that be the last commit?

**Comment by miroslavveljanoski** [comment]
@snicoll @HazemBittar Is it a mistake that my issue is closed? I want to finish the project today and update the issue

**Comment by snicoll** [comment]
> Is it a mistake that my issue is closed?

No it isn't. I think you are done with the remark on the commit not having a reference to an issue. I don't think it is wise to ask you to redo all your commits just for that so that's why I've closed your issue and flagged it as done.

>  I'm not sure in which commit message should I put that extra message

The one that closes the issue. Something we haven't talked about much but if you work on issue with id 4, you create a branch for it, experiment and then merge that branch. Ideally you wouldn't have lots of commits there but a single one with `Closes #4` at the end of the commit message. If you need to have separate commits then you could decide to have `See #4` for all the intermediate commits and `Closes #4` for the last one. Doing so might generate quite a lot of noise in the issue (as each such commit would have a reference) and it would be hard for others to track what was changed. That's why we usually recommend a single commit if possible, especially if the task is small as it is the case here.

**Comment by miroslavveljanoski** [comment]
@snicoll For the project, I decided to put the styling in one (last) step in my development strategy and therefore I will have one issue according to the instructions. Since the styling for the whole project is not a pretty small task I would probably have several commits in that branch...So, is it a bad practice to put such a big task in one step in the development strategy or in a real situation I would probably have several issues related to the same step, and doing a single commit per issue?

**Comment by snicoll** [comment]
Doing one story for the whole styling of the site is not a good idea. Each step in your development strategy must provide a final result that « as a user of the site » can see.

Read your user stories again. If the purpose of one is that the user can see X, it must do that including whatever styling is necessary. 

I actually missed that during review.

**Comment by miroslavveljanoski** [comment]
Yes, that makes sense. But I just follow and working according to the video where the HTML structure for all pages is done first and after that the styling for the pages

**Comment by snicoll** [comment]
That was a way to show you how technically you can complete the site itself. We're very much more focused on the process than the actual technical tasks and splitting the work in separate steps that add a feature to the site is what matters. 

Re-reading your dev strategy, you need to be show the site at step 3 for instance and have all 3 features to be fully demonstrated. If you do styling at the end that won't achieve that.
